# Generated by Django 5.1.3 on 2024-11-07 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("predict", "0005_auto_20201215_2054"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="user",
        ),
    ]
